### ISSUE TITLE
Filter out double-pressed "ring key"

### ISSUE THREAD

**Issue by harry-gibson** [lelandpaul/virtual-ringing-room#105]
A lot of our difficulties learning to use RR occur when a bell is accidentally double-rung i.e. someone presses their key twice quickly (maybe because of a slightly laggy response or just by accident), they end up on wrong stroke - and then often "correct" it by pressing a third time, at which a pileup occurs! This seems to account for about 90% of our failures at the moment! 

I wonder if the ability to filter for this would be useful? Reject a key press if that key was last pressed within the last e.g. 250ms. Something like the attached patch is what I mean, would probably need some UI to turn it on/off/adjust the delay? 

[add_key_bounce_rejection.zip](https://github.com/lelandpaul/virtual-ringing-room/files/4702738/add_key_bounce_rejection.zip)

**Comment by BrynMarieR** [comment]
Hi Harry -- thanks for the feedback and the patch. Agreed that the current set-up is not ideal! That's what we've been finding the last few weeks as well. It's on our list for sure and we're planning it for the release after this one; currently sprinting to get set-up for an influx of users from the BBC interview airing tomorrow. We'll close this when it's in!

**Comment by BrynMarieR** [comment]
Comment for myself: Tune down to 250ms, 500ms is too aggressive.

**Comment by BrynMarieR** [comment]
Fixed in latest PR.
