### ISSUE TITLE
Handbell-oriented key bindings

### ISSUE THREAD

**Issue by apjanke** [lelandpaul/virtual-ringing-room#118]
I tried out Ringing Room, ringing hand bells with some of the Trinity people, a while back. Nice tool!

I had some difficulty with the default key bindings, though: the default of binding the number keys to the corresponding bells doesn't work that great for hand bells, where you're ringing two bells at the same time, and the one with the higher number is in your left hand. To ring bells 3 and 4 effectively, I had to turn my keyboard upside down, and then keep my hands close together.

Could we add additional keybindings more suitable for hand ringing that would allow you to keep your hands in a more natural ringing position on the keyboard? Something like "Z" for the left-hand bell, and "?" for the right-hand bell, based on 

Related to #73, but distinct: I think it would be nice to have hand-oriented bindings exist as defaults, and not just as a customizable option.

**Comment by BrynMarieR** [comment]
Have you tried using the [f] and [j] key bindings? Those map to the homerow for QWERTY users (though we know there's an issue for other keyboard layouts). Then [f] rings the one with the higher number and [j] the one with the lower.

**Comment by apjanke** [comment]
Oh! I didn't know about those. Yes, that works.
