### ISSUE TITLE
No confirmation for sent password-reset email, even with invalid email address

### ISSUE THREAD

**Issue by apjanke** [lelandpaul/virtual-ringing-room#121]
When you request a password-reset email, there's no confirmation page, including when you enter an email that does not have an associated Ringing Room account. (E.g. try resetting the password for "bogus@example.com".) Maybe it should show a brief confirmation page saying "If there's an account with that email address, a reset email has been sent", so users know they might have entered a bad email address, and to not expect the email to show up if they don't already have an account?

**Comment by BrynMarieR** [comment]
Just merged that to master today, expect to see in next release! :)

**Comment by apjanke** [comment]
:+1:
