### ISSUE TITLE
US-hosted instance for North American ringers?

### ISSUE THREAD

**Issue by apjanke** [lelandpaul/virtual-ringing-room#123]
Hi, Ringing Room folks,

I'm hearing from some users that latency is one of the main issues with Ringing Room, and this seems to be the case for me too. I'm in Brooklyn, NY, US. Looks like ringingroom.com is hosted in London, UK. That means that North American ringers are eating the transatlantic cable latency penalty.

My ping to ringingroom.com from my NYC apartment is 100 ms. Ouch! That seems like too much latency to do good striking.

```
$ ping ringingroom.com
PING ringingroom.com (159.65.95.115): 56 data bytes
64 bytes from 159.65.95.115: icmp_seq=0 ttl=51 time=102.491 ms
64 bytes from 159.65.95.115: icmp_seq=1 ttl=51 time=94.652 ms
```

Would it be worthwhile to consider a separate US-hosted `na.ringingroom.com` instance for North American ringers to use, so they could get nicer latency on it? How are you doing your hosting now? Is that documented somewhere?

**Comment by apjanke** [comment]
Actually, a question: is all the network traffic for sending bell-ringing events going through and mediated by the server? Or are the clients using websockets or something like to do direct peer-to-peer communication?

**Comment by apjanke** [comment]
And I just learned from your facebook page that `na.ringingroom.com` is already a thing.

```
$ ping na.ringingroom.com
PING na.ringingroom.com (167.172.227.47): 56 data bytes
64 bytes from 167.172.227.47: icmp_seq=0 ttl=53 time=19.268 ms
64 bytes from 167.172.227.47: icmp_seq=1 ttl=53 time=22.573 ms
64 bytes from 167.172.227.47: icmp_seq=2 ttl=53 time=25.473 ms
```

Nevermind!

**Comment by BrynMarieR** [comment]
An answer regardless to "is all the network traffic for sending bell-ringing events going through and mediated by the server?" -- short answer, yes! Ringing Room uses TCP (web sockets with flask socketio). Every "rope pull" gets sent up to the server and then back down to the client to hear a bell ring and see an image flip.

**Comment by apjanke** [comment]
Hey, I got all your sweet RedBubble Ringing Room swag in the mail this week. Right on!
