### ISSUE TITLE
Where has the list of signal types gone?

### ISSUE THREAD

**Issue by kneasle** [lelandpaul/virtual-ringing-room#154]
They seem to have disappeared from `README.md` in `trunk`.  I think that they were very useful documentation (I certainly used them when figuring out how to contribute).  Same goes for the code layout (though diagrams like that tend to diverge from the actual code - I'm fairly tempted to make a python script to keep them up to date but haven't got round to it yet).

However, they are pretty much only useful for people interested in contributing, so an idea is to put them in a 'contributing' file like I did [for Wheatley](https://github.com/kneasle/wheatley/blob/master/CONTRIBUTING.md).  All the technical detail now occupies a [few lines](https://github.com/kneasle/wheatley#contributing) of the `README.md`.

**Comment by BrynMarieR** [comment]
We're in the active process of updating the README -- sorry you were interrupted! Things should be back in useful order by EOD today, American time. :)

**Comment by kneasle** [comment]
:laugh: I did wonder - the readme did look oddly incomplete! The Wheatley branch still has the list and that's the thing I was worried about - I'll probably rebase `integrate-wheatley` to `trunk` before merging since then it'll contain the new changes, as well as giving an opportunity to remove my continual fixes and U-turns so I don't clutter the commit history.

**Comment by BrynMarieR** [comment]
Alright, the brand-new API (still in alpha!) is on `trunk`, as is a fresh new README. A rebase now is probably a good idea (wanted to wait to suggest it until after we made these changes).

As a heads-up, though, we are planning on doing a total code-base review sometime in the next few weeks, which may or may not lead you to want to do another rebase. We'll keep in touch, though.

**Comment by kneasle** [comment]
OK that sounds like a good plan. I don't think the Wheatley PR will take too much longer - I'd hope to get that merged before any big code changes, but if it's the only thing you're waiting for then go ahead and I'll deal with any ensuing merge conflicts.

I'd also be happy to put in my penny's worth for the code review - I'm not a hugely experienced software engineer and I don't want you to feel like I'm intruding on the project, but I have had to find my way round the code base a lot of times to contribute PRs so I have a fairly objective view of the code as well as the parts that are confusing for new contributers.  But it's up to you - let me know what you want to do (also because I'm not sure if github sends emails for comments on closed issues).

**Comment by kneasle** [comment]
P.S. I like the new README!

**Comment by BrynMarieR** [comment]
Thanks, I think we'll take you up on that. I'm planning to do a full review in a branch sometime in the next two weeks, which I'll then make a PR for and assign you as reviewer. If there are any other big changes you'd like to see, you can repeat the process -- this is the most streamlined thing I can think of for doing a full code review outside of "new code".

**Comment by kneasle** [comment]
That sounds like a good plan - I'll make sure not to make any PRs whilst the code review is happening :).
