### ISSUE TITLE
Caps lock insensitivity

### ISSUE THREAD

**Issue by mylesdakan** [lelandpaul/virtual-ringing-room#50]
Map capital and lowercase letters to the same shortcuts.

**Comment by betzevim** [comment]
Is this something that it is doing and shouldn't be, or that it isn't doing and should be?

**Comment by mylesdakan** [comment]
Currently the shortcuts are only lowercase letters.

**Comment by lelandpaul** [comment]
This will be fixed in version 20.20. Thanks!
