### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by lelandpaul** [lelandpaul/virtual-ringing-room#69]
Add a volume control to the Tower page control panel.

**Comment by JPumphrey** [comment]
Will users be able to tell which controls change state for them, vs for the whole tower?

**Comment by lelandpaul** [comment]
Fair point — I have had reports of some confusion on this point. We should consider visually demarcating two sections of the tower controls and adding headers / documentation.

Once our tower-captaincy is implemented, the global controls will not be visible to non-tower-captain users; however, we do want to retain the ability for towers with no designated tower captain, so this demarcation will still be useful. We'll give some thought to this.

**Comment by JPumphrey** [comment]
I'm picking this up, but I don't have the permissions to assign it to myself
