### ISSUE TITLE
Debounce keypresses

### ISSUE THREAD

**Issue by lelandpaul** [lelandpaul/virtual-ringing-room#78]
Currently, hotkeys have two types:

- "Call" hotkeys ([b],[n], etc.) are rate-limited once per second. Holding down the key will result in one call per second.
- "Ringing" hotkeys ([f], [space], etc.) have no rate-limiting. Holding down the key will result in very rapid repeated ringing.

We want to implement the following behavior for both types: The intended event happens on key-down, and no further events of that type are possible (on that client) until key-up.

**Comment by JPumphrey** [comment]
Which browser and OS are you seeing this in? I can't repro

**Comment by lelandpaul** [comment]
Whoops — that's because I put a fix in but failed to close this issue.

I'm going to leave this open for now, though, because I want to confirm that the debounce fix isn't causing other issues.

**Comment by lelandpaul** [comment]
The debounce works better now, so I'm closing this issue.
