### ISSUE TITLE
sass error

### ISSUE THREAD

**Issue by robinlennox** [lelandpaul/virtual-ringing-room#95]
Hi,

When I run:

`sass app/static/sass/:app/static/css/. `

I get the following error message:

```
sass --update ["app/static/sass/:app/static/css/", "."]
  directory app/static/css
      error app/static/sass/circle.scss (Line 97: Incompatible units: 'rem' and 'vh'.)
      write app/static/css/global_design.css
      write app/static/css/global_design.css.map
      error app/static/sass/circle.scss (Line 97: Incompatible units: 'rem' and 'vh'.)
      error app/static/sass/static.scss (Line 24: Incompatible units: 'vh' and 'rem'.)
      error ./app/static/sass/circle.scss (Line 97: Incompatible units: 'rem' and 'vh'.)
      error app/static/sass/circle.scss (Line 97: Incompatible units: 'rem' and 'vh'.)

```

**Comment by lelandpaul** [comment]
Are you using [dart-sass](https://github.com/sass/dart-sass)? The Ruby version of sass available on both apt and homebrew by default is now deprecated; one of our recent updates started using Sass syntax that was incompatible with the Ruby version.

**Comment by robinlennox** [comment]
@lelandpaul Thanks for getting back. The issue was solved by install sass via npm: npm install -g sass.
